the_plots_labels:
  - Time                 #0
  - 'clusters'
  - 'all clusters'
the_plots_formats:
  - [0,2,1]
#y_labels: ['# of requests', '# of requests','','% of utilization of workers']
#file_suffixes:
#  - errors
line_widths:
  - [2,2,5,2,2,2,2,2,2,2,2]
default_colors: &default_colors ["black", "cyan", "blue","red","green",
                                 "black", "blue","red",
                                 "magenta", "brown", "orange", "green", "brown"]
the_plots_colors:
  - *default_colors
legend_position:
  - "upper right"
  - "upper right"
legend_size: 12
force_limit_plot_y:
#  1: 140
#   3: 1000
#  4: 35
#  0: 40
#  3: 80
start_plot_x:
  0: 90
force_limit_plot_x:
#  0: 820
#  1: 800
#  3: 800
sampling:
  - true
samplingField:
  - seed
hlines:
  0: [[1, { linestyle: '--' }]]
title_prefix: ''
excluded_titles:
line_styles:
  - ['solid', 'solid', 'solid']
format: "pdf"